### PR TITLE
method name convention

### PR DESCRIPTION
**Pull request by ghost**
method name starting with Caps
Appquit -> appquit
Open -> open

### CODE REVIEW

**Comment by chaudhary19** [comment]
kindly look at the new changes made and checkout their convention too so that I can merge it properly

**Comment by ghost** [comment]
Okay sir

**Comment by ghost** [comment]
Sir, Can improving the readability of the code according to the PEP 8 guidelines be considered as a PR?

**Comment by chaudhary19** [comment]
We will consider it as a PR for this contest

**Pull request closed without merging**
